sudo: required
services:
  - docker

before_install:
  - docker build -t alexlee27/docker-practice -f Dockerfile.dev .

script:
  - docker run -e CI=true alexlee27/docker-practice npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-205441520836"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
